# Generated by Django 5.2.1 on 2026-04-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_conge_restant'),
        ('accounts', '0006_alter_qrdynamic_id_alter_user_id'),
    ]

    operations = [
    ]
