# Generated by Django 5.2.1 on 2026-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0008_alter_absence_statut_alter_absence_typeabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qrcodesession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
